name: SilentVoice CI

on:
  push:
    branches:
      - "**"

jobs:
  first-job:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Welcome
        run: echo "Welcome to SilentVoice CI!"

      - name: Show Repository Files
        run: ls -la

      - name: Show Current Directory
        run: pwd

      - name: Finished
        run: echo "Workflow Completed Successfully!"